sudo: required
services:
  - docker

before_install:
  - docker build -t rutvikpensionwar/docker-react -f Dockerfile.dev .

script:
  - docker run rutvikpensionwar/docker-react npm run test -- --coverage
