sudo: required
services:
  - docker

before_install:
  - docker build -t rutvikpensionwar/docker_react -f Dockerfile.dev .

script:
  - docker run rutvikpensionwar/docker_react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  name: "docker_react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-2-271678594677"
  bucket_path: "docker_react"
  on:
    branch: master
  access_key_id: 
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"